extern string commonHdr_s;
extern string commonFuncHdr_s;
extern string istartHdr_s;
extern string commonConnHdr_s;

extern string fsmUdType_s;
extern string fsmFuncRetType_s;
extern string spc_s;
extern string opPar_s;
extern string clPar_s;
extern string opBrc_s;
extern string clBrc_s;
extern string fsmFuncDefInit_s;
extern string fsmFuncMsgInit_s;
extern string fsmFuncCrInit_s;
extern string here_s;
extern string fsmStPref;
extern string svcName;
// Functions
void prFSMDataClass();
void prSTT(void);
void prStateLine(void);
void prInputList(void);
void prStateList(void);
void prTail(void);
void handleElseCaseEnd(void);
void decend(void);
void handleElseCaseStart(void);
void handleCaseEnd(void);
void handleDecisionStart(string dec);
void handleCaseStart(string cs);
void handleAltStart(string alt);
void altend(void);
void handleStop(void);
void handleTask(string mq);
void handleJoinStmt(string jn);
void handleNewConn(string in);
void handleCallStmt(int type, string cs);
void handleNewState(string ns);
void handleNewInput(string in);
void handleEndState(void);
void svcInit(string s);
void addState(string st);
bool isState(string st);
void handleNextState(string ns);
void prNextState(string ns);
void addStartFuncStart(void);
void addCommHdr();
void fstart(void);
void fend(void);
bool isInput(string in);
void addInput(string in);
